# @package _global_

defaults:
  - arch: hrm_v1
  - _self_

hydra:
  output_subdir: null

# Data
dataset_dir: hrm-language/data/gsm8k-tokenized

# Hyperparams
global_batch_size: 8
block_size: 512
epochs: 10
grad_accum_steps: 1

lr: 1e-4
lr_min_ratio: 1.0
lr_warmup_steps: 2000

# Standard hyperparameter settings for LM
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
